POST https://{{$dotenv HOST}}/v1/kitchen/messaging/ingress HTTP/1.1
Content-Type: application/json
X-API-KEY: {{$dotenv HOST_API_KEY}}

<@ ./sample-order.json

###

# @name authz
POST https://kitchensync.auth.us-east-1.amazoncognito.com/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
# Authorization: Basic {{$dotenv SAMPLE_CLIENT_ID}} {{$dotenv SAMPLE_CLIENT_SECRET}}

grant_type=client_credentials
&scope=kitchensync/post
&client_id={{$dotenv SAMPLE_CLIENT_ID}}
&client_secret={{$dotenv SAMPLE_CLIENT_SECRET}}

###

POST https://{{$dotenv APIGATEWAY}}/v1/messaging/publish HTTP/1.1
Content-Type: application/json
Authorization: {{authz.response.body.token_type}} {{authz.response.body.access_token}}
X-SOURCE: doordash
X-EVENT-KIND: Order.Notification
X-ENVIRONMENT: Sandbox

<@ ./sample-order.json

###

POST https://{{$dotenv APIGATEWAY}}/v2/resthooks/events HTTP/1.1
Content-Type: application/json
Authorization: {{authz.response.body.token_type}} {{authz.response.body.access_token}}
X-SOURCE: doordash
X-EVENT-KIND: Order.Notification
X-ENVIRONMENT: Sandbox

<@ ./sample-order.json
