POST https://kitchensync.auth.us-east-1.amazoncognito.com/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
# Authorization: Basic {{$dotenv SAMPLE_CLIENT_ID}} {{$dotenv SAMPLE_CLIENT_SECRET}}

grant_type=client_credentials
&scope=kitchensync/post
&client_id={{$dotenv SAMPLE_CLIENT_ID}}
&client_secret={{$dotenv SAMPLE_CLIENT_SECRET}}

###

POST https://{{$dotenv HOST}}/v1/kitchen/messaging/ingress HTTP/1.1
Content-Type: application/json
X-API-KEY: {{$dotenv HOST_API_KEY}}

<@ ./sample-order.json

###

POST https://{{$dotenv APIGATEWAY}}/v1/messaging/publish HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJsaDNDZXNMNFhoSGpacks2bzNtaGFtUFRLOHdOZ21YS216cXBoVmpybVdZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzNDIxcGhja3NjZzdxdWdpdHVzYzF2azI3byIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoia2l0Y2hlbnN5bmNcL3Bvc3QiLCJhdXRoX3RpbWUiOjE3MjEwMTgyNTksImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xXzVKcGRVNzgyUyIsImV4cCI6MTcyMTEwNDY1OSwiaWF0IjoxNzIxMDE4MjU5LCJ2ZXJzaW9uIjoyLCJqdGkiOiIxODA3ZTZhNy1mYjMzLTQyZDgtOGU2Yi0yYWFjM2E3MThlM2EiLCJjbGllbnRfaWQiOiIzNDIxcGhja3NjZzdxdWdpdHVzYzF2azI3byJ9.Hgvgk9BDwCIe-9gHaprBHV2KOT-56roJAxG8x1BdyfLiyTiaGxBhxUWUhYjHL41BL0io-FgtijIvA3iX0yPLPgsQNYvukj-N-9YGUSlX6sru-485kCieV9ob6MhuYkohsyxr7qlFllrJIvCO7LcoaGyULBQGllrh5xHOd-B__cpbQeUN01EhbTg6UgIxMuhpFxSTM4jPgEdd6jxnLCUDAxknfZN5xqWwURcytudv1yPvuQCbqbEWKWgBJ4jQvduWo1yAWUAE7yEI-kcM1-A99nz7UvFCWj4do8gyXD1p-ARYHbSzYhvJ2m-KLzKAeHTMJBlZex7XYo5ITUN9uKqiVg
X-SOURCE: doordash
X-EVENT-KIND: Order.Notification
X-ENVIRONMENT: Sandbox

<@ ./sample-order.json

###

POST https://{{$dotenv APIGATEWAY}}/v2/resthooks/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJsaDNDZXNMNFhoSGpacks2bzNtaGFtUFRLOHdOZ21YS216cXBoVmpybVdZPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzNDIxcGhja3NjZzdxdWdpdHVzYzF2azI3byIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoia2l0Y2hlbnN5bmNcL3Bvc3QiLCJhdXRoX3RpbWUiOjE3MjEwMTgyNTksImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xXzVKcGRVNzgyUyIsImV4cCI6MTcyMTEwNDY1OSwiaWF0IjoxNzIxMDE4MjU5LCJ2ZXJzaW9uIjoyLCJqdGkiOiIxODA3ZTZhNy1mYjMzLTQyZDgtOGU2Yi0yYWFjM2E3MThlM2EiLCJjbGllbnRfaWQiOiIzNDIxcGhja3NjZzdxdWdpdHVzYzF2azI3byJ9.Hgvgk9BDwCIe-9gHaprBHV2KOT-56roJAxG8x1BdyfLiyTiaGxBhxUWUhYjHL41BL0io-FgtijIvA3iX0yPLPgsQNYvukj-N-9YGUSlX6sru-485kCieV9ob6MhuYkohsyxr7qlFllrJIvCO7LcoaGyULBQGllrh5xHOd-B__cpbQeUN01EhbTg6UgIxMuhpFxSTM4jPgEdd6jxnLCUDAxknfZN5xqWwURcytudv1yPvuQCbqbEWKWgBJ4jQvduWo1yAWUAE7yEI-kcM1-A99nz7UvFCWj4do8gyXD1p-ARYHbSzYhvJ2m-KLzKAeHTMJBlZex7XYo5ITUN9uKqiVg
X-SOURCE: doordash
X-EVENT-KIND: Order.Notification
X-ENVIRONMENT: Sandbox

<@ ./sample-order.json
